"use strict";
window.CF=window.CF||{};
CF.campaigns=(()=>{
 const validEmail=value=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value||"").trim());
 let selected=new Set(),cancelled=false,activeCampaignId="";
 const escape=CF.escape;
 const recipientRows=customers=>customers.map(customer=>{const valid=validEmail(customer.email),checked=selected.has(customer.customerId);return `<tr><td><input type="checkbox" data-campaign-customer="${customer.customerId}" ${checked?"checked":""} ${valid?"":"disabled"}></td><td>${escape(customer.name)}</td><td>${escape(customer.email||"No email")}</td><td>${escape(customer.mobile||"—")}</td><td>${valid?"Eligible":"No valid email"}</td></tr>`;}).join("");
 const historyRows=campaigns=>campaigns.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,10).map(c=>`<tr><td>${new Date(c.createdAt).toLocaleString("en-IN")}</td><td>${escape(c.templateName)}</td><td>${c.total}</td><td>${c.sent}</td><td>${c.failed}</td><td>${escape(c.status)}</td><td>${c.failed?`<button data-retry-campaign="${c.campaignId}">Retry failed</button>`:"—"}</td></tr>`).join("")||`<tr><td colspan="7" class="empty-cell">No campaign history.</td></tr>`;
 const render=async()=>{const [customers,templates,campaigns]=await Promise.all([CF.db.getAll("customers"),CF.db.getAll("emailTemplates"),CF.db.getAll("emailCampaigns")]),active=templates.filter(t=>t.isActive!==false),eligible=customers.filter(c=>validEmail(c.email));selected=new Set([...selected].filter(id=>eligible.some(c=>c.customerId===id)));return `<article class="notice"><strong>Individual delivery</strong><br>Every selected customer receives a separate email through the existing secure email service. Invalid and missing addresses cannot be selected.</article><div class="section-grid"><article class="card"><h2 class="section-title">Create Bulk Email Campaign</h2><div class="form-grid"><label class="wide">Email Template<select id="campaignTemplate"><option value="">Select an active template</option>${active.map(t=>`<option value="${t.templateId}">${escape(t.name)} — ${escape(t.category||"General")}</option>`).join("")}</select></label><label class="wide">Search customers<input id="campaignSearch" placeholder="Name, email or mobile"></label></div><div class="form-actions" style="margin-top:14px"><button type="button" class="secondary" id="selectAllCampaign">Select all eligible</button><button type="button" class="secondary" id="clearCampaignSelection">Unselect all</button><button type="button" class="secondary" id="previewCampaign" disabled>Preview email</button><button type="button" class="primary" id="sendCampaign" disabled>Send selected</button></div><p id="campaignSelection" class="muted">0 selected of ${eligible.length} eligible customers.</p></article><aside class="card"><h2 class="section-title">Sending Progress</h2><div id="campaignProgress" class="muted">Choose a template and recipients to begin.</div><button type="button" class="secondary" id="cancelCampaign" hidden>Stop after current email</button></aside></div><article class="card table-card"><table><thead><tr><th></th><th>Customer</th><th>Email</th><th>Mobile</th><th>Status</th></tr></thead><tbody id="campaignCustomers">${recipientRows(customers)}</tbody></table></article><article class="card table-card"><h2 class="section-title">Campaign History</h2><table><thead><tr><th>Sent</th><th>Template</th><th>Total</th><th>Success</th><th>Failed</th><th>Status</th><th></th></tr></thead><tbody>${historyRows(campaigns)}</tbody></table></article>`;};
 const updateUi=customers=>{const validCount=[...selected].filter(id=>customers.some(c=>c.customerId===id&&validEmail(c.email))).length,ready=validCount>0&&Boolean(document.getElementById("campaignTemplate")?.value);document.getElementById("campaignSelection").textContent=`${validCount} selected of ${customers.filter(c=>validEmail(c.email)).length} eligible customers.`;document.getElementById("sendCampaign").disabled=!ready;document.getElementById("previewCampaign").disabled=!ready;};
 const preview=async()=>{const template=await CF.db.get("emailTemplates",document.getElementById("campaignTemplate").value),customer=(await CF.db.getAll("customers")).find(c=>selected.has(c.customerId));if(!template||!customer)return;const variables=await CF.emailTemplates.contextFor(customer),subject=CF.dues.replaceVariables(template.subject,variables),html=CF.dues.templateHtml(CF.emailTemplates.renderTemplate(template),variables);if(window.Swal)await Swal.fire({title:escape(subject),html:`<div style="max-height:65vh;overflow:auto;text-align:left">${html}</div>`,width:760,showCloseButton:true});else{const win=window.open("","_blank");win.document.write(`<title>${escape(subject)}</title>${html}`);win.document.close();}};
 const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
 const sendOne=async(template,customer)=>{const variables=await CF.emailTemplates.contextFor(customer),subject=CF.dues.replaceVariables(template.subject,variables),html=CF.dues.templateHtml(CF.emailTemplates.renderTemplate(template),variables);let lastError;for(let attempt=0;attempt<2;attempt++){try{await CF.dues.sendEmail({to:customer.email,customerName:customer.name||"",subject,html,errorLabel:"Campaign email"});return;}catch(error){lastError=error;if(attempt===0&&navigator.onLine!==false)await wait(700);}}throw lastError;};
 const progress=(total,sent,failed)=>{const node=document.getElementById("campaignProgress");if(node)node.innerHTML=`Sending ${Math.min(sent+failed+1,total)} / ${total}<br>Success: ${sent}<br>Failed: ${failed}<br>Remaining: ${total-sent-failed}`;};
 const run=async({template,customers,campaignId,retry=false})=>{cancelled=false;activeCampaignId=campaignId;let sent=0,failed=0;const cancel=document.getElementById("cancelCampaign");if(cancel)cancel.hidden=false;for(const customer of customers){if(cancelled)break;progress(customers.length,sent,failed);const item={campaignRecipientId:CF.id(),campaignId,customerId:customer.customerId,customerName:customer.name||"",email:customer.email,status:"sending",createdAt:new Date().toISOString()};try{await sendOne(template,customer);item.status="sent";item.sentAt=new Date().toISOString();sent++;}catch(error){item.status="failed";item.error=CF.dues.messageForError(error);item.failedAt=new Date().toISOString();failed++;}await CF.db.put("emailCampaignRecipients",item);await CF.db.put("emailCampaigns",{...(await CF.db.get("emailCampaigns",campaignId)),sent,failed,status:cancelled?"Cancelled":"Sending",updatedAt:new Date().toISOString()});}
 const status=cancelled?"Cancelled":failed?"Completed with failures":"Completed",campaign=await CF.db.get("emailCampaigns",campaignId);await CF.db.put("emailCampaigns",{...campaign,sent,failed,status,completedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});if(cancel)cancel.hidden=true;const node=document.getElementById("campaignProgress");if(node)node.innerHTML=`<strong>Bulk email ${status.toLowerCase()}</strong><br>${customers.length} selected<br>${sent} sent successfully<br>${failed} failed`;CF.toast(`Bulk email ${status.toLowerCase()}`,failed?"error":"info");activeCampaignId="";if(!retry)setTimeout(CF.router.render,900);};
 const confirmSend=async()=>{const customers=(await CF.db.getAll("customers")).filter(c=>selected.has(c.customerId)&&validEmail(c.email)),template=await CF.db.get("emailTemplates",document.getElementById("campaignTemplate").value);if(!template||template.isActive===false||!customers.length)return;const confirmed=window.Swal?await Swal.fire({title:"Send bulk email?",text:`You are about to send this email to ${customers.length} customers. Continue?`,icon:"warning",showCancelButton:true,confirmButtonText:"Send"}).then(result=>result.isConfirmed):confirm(`You are about to send this email to ${customers.length} customers. Continue?`);if(!confirmed)return;const now=new Date().toISOString(),campaign={campaignId:CF.id(),templateId:template.templateId,templateName:template.name,total:customers.length,sent:0,failed:0,status:"Sending",createdAt:now,updatedAt:now};await CF.db.put("emailCampaigns",campaign);run({template,customers,campaignId:campaign.campaignId});};
 const retry=async id=>{const campaign=await CF.db.get("emailCampaigns",id),template=await CF.db.get("emailTemplates",campaign?.templateId),records=(await CF.db.getAll("emailCampaignRecipients")).filter(item=>item.campaignId===id&&item.status==="failed"),customers=await Promise.all(records.map(item=>CF.db.get("customers",item.customerId)));if(!template||!customers.length)return CF.toast("No failed recipients available to retry.","error");const now=new Date().toISOString(),retryCampaign={campaignId:CF.id(),templateId:template.templateId,templateName:`${template.name} (retry)`,total:customers.length,sent:0,failed:0,status:"Sending",createdAt:now,updatedAt:now};await CF.db.put("emailCampaigns",retryCampaign);run({template,customers:customers.filter(Boolean),campaignId:retryCampaign.campaignId,retry:true});};
 const bind=()=>{Promise.all([CF.db.getAll("customers"),CF.db.getAll("emailTemplates")]).then(([customers])=>{const body=document.getElementById("campaignCustomers"),search=document.getElementById("campaignSearch");document.getElementById("campaignTemplate").addEventListener("change",()=>updateUi(customers));body.addEventListener("change",event=>{if(!event.target.matches("[data-campaign-customer]"))return;event.target.checked?selected.add(event.target.dataset.campaignCustomer):selected.delete(event.target.dataset.campaignCustomer);updateUi(customers);});search.addEventListener("input",()=>{const query=search.value.toLowerCase();body.innerHTML=recipientRows(customers.filter(c=>[c.name,c.email,c.mobile].join(" ").toLowerCase().includes(query)));});document.getElementById("selectAllCampaign").addEventListener("click",()=>{customers.filter(c=>validEmail(c.email)).forEach(c=>selected.add(c.customerId));body.innerHTML=recipientRows(customers);updateUi(customers);});document.getElementById("clearCampaignSelection").addEventListener("click",()=>{selected.clear();body.innerHTML=recipientRows(customers);updateUi(customers);});document.getElementById("previewCampaign").addEventListener("click",preview);document.getElementById("sendCampaign").addEventListener("click",confirmSend);document.getElementById("cancelCampaign").addEventListener("click",()=>{cancelled=true;});document.querySelectorAll("[data-retry-campaign]").forEach(button=>button.addEventListener("click",()=>retry(button.dataset.retryCampaign)));updateUi(customers);});};
 return {render,bind};
})();
