"use strict";
window.CF=window.CF||{};
CF.pdf=(()=>{
 const formatDate=value=>{const m=String(value||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}-${m[2]}-${m[1]}`:CF.escape(value||"");};
 const settingsFor=async()=>Object.fromEntries((await CF.db.getAll("settings")).map(x=>[x.key,x.value]));
 const renderInvoice=(invoice,settings)=>{const i=invoice,s=settings,gst=i.invoiceType==="GST",customer=i.customerSnapshot||{},template=s.invoiceTemplate||"fullA4",terms=String(s.invoiceTerms||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean),items=(i.items||[]).map((x,n)=>`<tr><td>${n+1}</td><td><b>${CF.escape(x.name)}</b>${x.description?`<br><small>${CF.escape(x.description)}</small>`:""}${x.serialNo?`<br><small>Batch: ${CF.escape(x.serialNo)}</small>`:""}</td>${gst?`<td>${CF.escape(x.hsn||"")}</td>`:""}<td>${x.qty}</td><td>${CF.formatCurrency(x.rate)}</td><td>${CF.formatCurrency(x.discount||0)}</td>${gst?`<td>${x.gst||0}%</td>`:""}<td>${CF.formatCurrency(x.amount)}</td></tr>`).join(""),company=CF.escape(s.companyName||"Click & Fix Billing Pro"),address=CF.escape(s.address||"").replace(/\n/g,"<br>"),customerAddress=CF.escape(customer.address||"").replace(/\n/g,"<br>"),detail=`<div><b>${CF.escape(i.customerName||customer.name||"")}</b><br>${customerAddress}${customer.mobile?`<br>${CF.escape(customer.mobile)}`:""}${customer.email?`<br>${CF.escape(customer.email)}`:""}</div>`,summary=`<div class="invoice-summary"><span>Subtotal <b>${CF.formatCurrency(i.subtotal)}</b></span>${gst?`<span>GST <b>${CF.formatCurrency(i.gstTotal)}</b></span>`:""}<span>Paid <b>${CF.formatCurrency(i.paid||0)}</b></span><span>Due <b>${CF.formatCurrency(i.due||0)}</b></span><strong>Grand Total ${CF.formatCurrency(i.grandTotal)}</strong></div>`,table=`<table class="invoice-items"><thead><tr><th>#</th><th>Description</th>${gst?"<th>HSN</th>":""}<th>Qty</th><th>Rate</th><th>Disc.</th>${gst?"<th>GST</th>":""}<th>Amount</th></tr></thead><tbody>${items}</tbody></table>`,footer=`<div class="invoice-footer"><div><b>Terms & Conditions</b><br>${terms.map(CF.escape).join("<br>")||"—"}</div><div><b>Delivery Terms</b><br>${CF.escape(i.deliveryTerms||s.defaultDeliveryTerms||"").replace(/\n/g,"<br>")||"—"}</div><div><b>Payment Status</b><br>${CF.escape(i.paymentStatus||"Unpaid")}</div></div>`,meta=`<div class="invoice-meta"><span><b>Invoice No.</b> ${CF.escape(i.invoiceNo)}</span><span><b>Date</b> ${formatDate(i.invoiceDate)}</span><span><b>Customer ID</b> ${CF.escape(customer.customerId||i.customerId||"")}</span></div>`;
  if(template==="halfA4")return `<article class="invoice-document invoice-half"><header><div><h1>${company}</h1><p>${address}<br>Phone: ${CF.escape(s.phone||"")}</p></div><div><h2>${gst?"TAX INVOICE":"INVOICE"}</h2>${meta}</div></header><section class="invoice-parties"><div><small>BILL TO</small>${detail}</div><div>${summary}</div></section>${table}<section class="invoice-foot-compact"><span>${CF.escape(i.amountWords||CF.amountWords(i.grandTotal))}</span><span>${CF.escape(i.paymentStatus||"Unpaid")}</span></section></article>`;
  if(template==="modernCompact")return `<article class="invoice-document invoice-modern"><header><div class="invoice-mark">CF</div><div><h1>${company}</h1><p>${address}</p></div><div><small>INVOICE</small><h2>${CF.escape(i.invoiceNo)}</h2><p>${formatDate(i.invoiceDate)}</p></div></header><section class="invoice-modern-grid"><div><small>TO</small>${detail}</div>${summary}</section>${table}<footer>${footer}</footer></article>`;
  if(template==="professionalBusiness")return `<article class="invoice-document invoice-professional"><header><div><small>CLICK & FIX TECHNOLOGIES</small><h1>${gst?"Tax Invoice":"Professional Invoice"}</h1><p>${company}<br>${address}<br>${CF.escape(s.email||"")}</p></div><div class="invoice-number"><b>INVOICE</b><strong>${CF.escape(i.invoiceNo)}</strong>${formatDate(i.invoiceDate)}</div></header><section class="invoice-parties"><div><small>CUSTOMER</small>${detail}</div><div><small>PAYMENT SUMMARY</small>${summary}</div></section>${table}<section class="amount-words"><b>Amount in words:</b> ${CF.escape(i.amountWords||CF.amountWords(i.grandTotal))}</section>${footer}</article>`;
  return `<article class="invoice-full"><h1 class="invoice-title">${gst?"Tax Invoice":"Invoice"}</h1><main class="invoice-frame"><section class="top-grid"><section class="seller"><p class="company-name">${company}</p><p>${address}<br>Phone: ${CF.escape(s.phone||"")}${s.gst?`<br>GSTIN/UIN: ${CF.escape(s.gst)}`:""}<br>Email: ${CF.escape(s.email||"")}</p><div class="party"><span>Buyer (Bill to)</span>${detail}</div></section><section class="metadata"><table><tbody><tr><td>Invoice No.<strong>${CF.escape(i.invoiceNo)}</strong></td><td>Dated<strong>${formatDate(i.invoiceDate)}</strong></td></tr><tr><td>Delivery Note<strong>${CF.escape(i.deliveryNote||"")}</strong></td><td>Mode/Terms of Payment<strong>${CF.escape(i.modeTerms||"")}</strong></td></tr><tr><td>Reference No.<strong>${CF.escape(i.referenceNo||"")}</strong></td><td>Destination<strong>${CF.escape(i.destination||"")}</strong></td></tr></tbody></table><div class="delivery-box">Terms of Delivery<br>${CF.escape(i.deliveryTerms||s.defaultDeliveryTerms||"").replace(/\n/g,"<br>")}</div></section></section><table class="items"><thead><tr><th>Sl.</th><th>Description of Goods</th>${gst?"<th>HSN/SAC</th>":""}<th>Quantity</th><th>Rate</th><th>Disc.</th>${gst?"<th>GST</th>":""}<th>Amount</th></tr></thead><tbody>${items}</tbody><tfoot><tr><td colspan="2">Total</td><td colspan="${gst?4:3}"></td><td class="money">${CF.formatCurrency(i.grandTotal)}</td></tr></tfoot></table><section class="summary"><div class="words"><b>Amount Chargeable (in words)</b>${CF.escape(i.amountWords||CF.amountWords(i.grandTotal))}</div><div class="balances"><div class="balance-row"><span>Previous Balance</span><b>${CF.formatCurrency(i.previousBalance||0)}</b></div><div class="balance-row"><span>Invoice Amount</span><b>${CF.formatCurrency(i.grandTotal)}</b></div><div class="balance-row"><span>Current Balance</span><b>${CF.formatCurrency(Number(i.previousBalance||0)+Number(i.due||0))}</b></div></div></section><section class="footer-grid">${footer}</section></main><p class="computer-note">This is a Computer Generated Invoice, does not require signature.</p></article>`;
 };
 const invoiceHtml=async id=>{const [invoice,settings]=await Promise.all([CF.db.get("invoices",id),settingsFor()]);if(!invoice)throw new Error("Invoice not found");return {invoice,settings,html:renderInvoice(invoice,settings)};};
 const printInvoice=async id=>{const {invoice,html}=await invoiceHtml(id),w=window.open("","_blank");if(!w)return CF.toast("Please allow pop-ups to print the invoice.","error");w.document.write(`<!doctype html><html><head><meta charset="utf-8"><base href="${location.href}"><title>${CF.escape(invoice.invoiceNo)}</title><link rel="stylesheet" href="css/invoice.css?v=9"></head><body class="print-invoice">${html}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),400);};
 const pdfAttachment=async id=>{if(!window.html2canvas||!window.jspdf?.jsPDF)throw new Error("PDF generator is unavailable. Check your internet connection and try again.");const {invoice,settings,html}=await invoiceHtml(id),host=document.createElement("div");host.className="print-invoice invoice-pdf-host";host.innerHTML=html;document.body.append(host);try{const canvas=await window.html2canvas(host.firstElementChild,{scale:2,useCORS:true,backgroundColor:"#ffffff"}),Pdf=window.jspdf.jsPDF,half=settings.invoiceTemplate==="halfA4",pdf=new Pdf({orientation:"p",unit:"mm",format:half?[210,148.5]:"a4"}),width=210,height=Math.min(half?148.5:297,canvas.height*width/canvas.width);pdf.addImage(canvas.toDataURL("image/jpeg",.92),"JPEG",0,0,width,height);return {filename:`Invoice-${invoice.invoiceNo}.pdf`,content:pdf.output("datauristring").split(",")[1]};}finally{host.remove();}};
 return {printInvoice,invoiceHtml,pdfAttachment,renderInvoice};
})();
