"use strict";
window.CF=window.CF||{};
CF.dues=(()=>{
 const WORKER_URL="https://shiny-night-8eadclickfix-reminder.clicknfixtechnologies.workers.dev/",REQUEST_TIMEOUT=20000;
 const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[character]);
 const replaceVariables=(template,variables,html=false)=>Object.entries(variables).reduce((result,[key,value])=>result.split(`{{${key}}}`).join(html?escapeHtml(value):String(value??"")),String(template??""));
 const formatDate=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString("en-IN"):"";
 const messageForError=error=>{if(error.name==="AbortError")return "Reminder request timed out. Please try again.";if(error instanceof TypeError)return navigator.onLine===false?"Internet Connection Required":"Could not connect to the reminder service.";return error.message||"Could not send reminder."};
 const templateHtml=(body,variables)=>{const source=String(body??""),hasHtml=/<[a-z][\s\S]*>/i.test(source),replaced=replaceVariables(source,variables,true);return hasHtml?replaced:replaced.replace(/\r?\n/g,"<br>");};
 const sendEmail=async({to,customerName,subject,html,errorLabel="Reminder"})=>{if(navigator.onLine===false)throw new Error("Internet Connection Required");const email=String(to||"").trim();if(!email)throw new Error("Customer Email Not Found");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("Customer Email Invalid");const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT);let response;try{response=await fetch(WORKER_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:email,customerName:customerName||"",subject,html}),signal:controller.signal});}finally{clearTimeout(timeout);}const raw=await response.text();let result;try{result=raw?JSON.parse(raw):{};}catch{if(!response.ok)throw new Error(`${errorLabel} service failed (${response.status}).`);throw new Error(`${errorLabel} service returned an invalid response.`);}if(!response.ok||result?.success===false)throw new Error(result?.message||result?.error||`${errorLabel} service failed (${response.status}).`);};
 const render=async()=>{const [customers,templates,reminders]=await Promise.all([CF.db.getAll("customers"),CF.db.getAll("emailTemplates"),CF.db.getAll("reminders")]),due=customers.filter(c=>Number(c.outstanding)>0).sort((a,b)=>b.outstanding-a.outstanding);return `<article class="notice"><strong>Manual reminders</strong><br>Select a customer and template. This saves a reminder record and opens a ready-to-send email draft. Brevo API sending can be connected from Settings later.</article><article class="card table-card"><table><thead><tr><th>Customer</th><th>Mobile</th><th>Email</th><th>Outstanding Due</th><th>Reminder</th></tr></thead><tbody>${due.map(c=>`<tr><td>${CF.escape(c.name)}</td><td>${CF.escape(c.mobile)}</td><td>${CF.escape(c.email||"No email")}</td><td>${CF.formatCurrency(c.outstanding)}</td><td><button data-remind="${c.customerId}">🔔 Remind</button></td></tr>`).join("")||`<tr><td colspan="5" class="empty-cell">No outstanding dues.</td></tr>`}</tbody></table></article><article class="card"><h2 class="section-title">Recent Reminder Activity</h2>${reminders.slice(-8).reverse().map(r=>`<p>${new Date(r.createdAt).toLocaleString("en-IN")} — ${CF.escape(r.customerName)} · ${CF.formatCurrency(r.due)}</p>`).join("")||"<p class='empty'>No reminders sent yet.</p>"}<input type="hidden" id="templateData" value="${CF.escape(JSON.stringify(templates))}"></article>`};
 const contextFor=async customer=>{const [invoices,payments,settings]=await Promise.all([CF.db.getAll("invoices"),CF.db.getAll("payments"),CF.db.getAll("settings")]),company=Object.fromEntries(settings.map(item=>[item.key,item.value])),customerInvoices=invoices.filter(invoice=>invoice.customerId===customer.customerId).sort((a,b)=>String(b.invoiceDate||"").localeCompare(String(a.invoiceDate||""))),invoice=customerInvoices.find(item=>Number(item.due)>0)||customerInvoices[0]||{},payment=payments.filter(item=>item.customerId===customer.customerId).sort((a,b)=>String(b.paymentDate||b.createdAt||"").localeCompare(String(a.paymentDate||a.createdAt||"")))[0]||{};return {customerName:customer.name||"",customerEmail:customer.email||"",customerMobile:customer.mobile||"",invoiceNo:invoice.invoiceNo||"",invoiceDate:formatDate(invoice.invoiceDate),dueDate:formatDate(invoice.dueDate||invoice.paymentDueDate||invoice.invoiceDate),amount:CF.formatCurrency(invoice.grandTotal||0),dueAmount:CF.formatCurrency(customer.outstanding||invoice.due||0),companyName:company.companyName||"Click & Fix Billing Pro",companyPhone:company.phone||"",companyEmail:company.email||"",companyAddress:company.address||"",bank:company.bank||"",upi:company.upi||"",paymentLink:company.paymentLink||"https://razorpay.me/@clicknfixtechnologies",mobile:customer.mobile||"",paymentStatus:invoice.paymentStatus||payment.status||""};};
 const send=async(button,customerId)=>{const originalLabel=button.textContent;button.disabled=true;button.textContent="Sending…";try{if(navigator.onLine===false)throw new Error("Internet Connection Required");const customer=await CF.db.get("customers",customerId),email=String(customer?.email||"").trim();if(!email)throw new Error("Customer Email Not Found");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("Customer Email Invalid");const templates=JSON.parse(document.getElementById("templateData")?.value||"[]"),template=templates[0]||{subject:"Payment reminder",body:"Dear {{customerName}},\n\nYour outstanding balance is {{dueAmount}}."},variables=await contextFor(customer),subject=replaceVariables(template.subject,variables),html=templateHtml(template.body,variables),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT);let response;try{response=await fetch(WORKER_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:email,customerName:customer.name||"",subject,html}),signal:controller.signal});}finally{clearTimeout(timeout);}const raw=await response.text();let result;try{result=raw?JSON.parse(raw):{};}catch{if(!response.ok)throw new Error(`Reminder service failed (${response.status}).`);throw new Error("Reminder service returned an invalid response.");}if(!response.ok||result?.success===false)throw new Error(result?.message||result?.error||`Reminder service failed (${response.status}).`);await CF.db.put("reminders",{reminderId:CF.id(),customerId:customer.customerId,customerName:customer.name,due:customer.outstanding,createdAt:new Date().toISOString(),status:"Email sent"});CF.toast("Reminder sent successfully");CF.router.render();}catch(error){console.error(error);CF.toast(messageForError(error),"error");}finally{button.disabled=false;button.textContent=originalLabel;}};
 const bind=()=>document.querySelectorAll("[data-remind]").forEach(button=>button.addEventListener("click",()=>send(button,button.dataset.remind)));
 return {render,bind,replaceVariables,templateHtml,messageForError,sendEmail};
})();
