"use strict";
window.CF=window.CF||{};
CF.reports=(()=>{
 let data={};
 const cards=()=>`<div class="stats"><div class="card"><span class="card-label">Total Sales</span><strong class="card-value card-accent">${CF.formatCurrency(data.sales)}</strong></div><div class="card"><span class="card-label">Total Purchase</span><strong class="card-value">${CF.formatCurrency(data.purchase)}</strong></div><div class="card"><span class="card-label">Total Stock</span><strong class="card-value">${CF.formatNumber(data.stock)}</strong></div><div class="card"><span class="card-label">Total Customers</span><strong class="card-value">${CF.formatNumber(data.customers.length)}</strong></div><div class="card"><span class="card-label">Total Due Amount</span><strong class="card-value">${CF.formatCurrency(data.due)}</strong></div></div>`;
 const stockRows=()=>data.products.map(p=>`<tr><td>${CF.escape(p.name)}</td><td>${CF.escape(p.productCode||"—")}</td><td>${CF.formatNumber(p.currentStock)}</td><td>${CF.formatNumber(p.minimumStock)}</td></tr>`).join("")||`<tr><td colspan="4" class="empty-cell">No products found.</td></tr>`;
 const customerRows=()=>data.customers.map(c=>`<tr><td>${CF.escape(c.name)}</td><td>${CF.escape(c.mobile||"—")}</td><td>${CF.escape(c.address||"—")}</td><td>${CF.formatCurrency(c.outstanding)}</td></tr>`).join("")||`<tr><td colspan="4" class="empty-cell">No customers found.</td></tr>`;
 const dueRows=()=>data.invoices.filter(i=>Number(i.due)>0).sort((a,b)=>b.invoiceDate.localeCompare(a.invoiceDate)).map(i=>`<tr><td>${CF.escape(i.customerName)}</td><td>${CF.escape(i.invoiceNo)}</td><td>${i.invoiceDate}</td><td>${CF.formatCurrency(i.grandTotal)}</td><td>${CF.formatCurrency(i.due)}</td></tr>`).join("")||`<tr><td colspan="5" class="empty-cell">No outstanding invoices.</td></tr>`;
 const render=async()=>{const [invoices,customers,products,purchases]=await Promise.all([CF.db.getAll("invoices"),CF.db.getAll("customers"),CF.db.getAll("products"),CF.db.getAll("purchases")]);data={invoices,customers,products,sales:invoices.reduce((t,i)=>t+Number(i.grandTotal||0),0),purchase:purchases.reduce((t,p)=>t+Number(p.total||0),0),stock:products.reduce((t,p)=>t+Number(p.currentStock||0),0),due:customers.reduce((t,c)=>t+Number(c.outstanding||0),0)};return `<div class="toolbar"><h2 class="section-title">Business Summary Report</h2><button class="primary" id="downloadReport">Download PDF</button></div>${cards()}<article class="card table-card"><h3 class="section-title">Product-wise Stock Summary</h3><table><thead><tr><th>Product</th><th>Product Code</th><th>Current Stock</th><th>Minimum Stock</th></tr></thead><tbody>${stockRows()}</tbody></table></article><article class="card table-card"><h3 class="section-title">Customer List</h3><table><thead><tr><th>Customer</th><th>Mobile</th><th>Address</th><th>Total Due</th></tr></thead><tbody>${customerRows()}</tbody></table></article><article class="card table-card"><h3 class="section-title">Invoice-wise Due Details</h3><table><thead><tr><th>Customer</th><th>Invoice No.</th><th>Invoice Date</th><th>Invoice Amount</th><th>Due Amount</th></tr></thead><tbody>${dueRows()}</tbody></table></article>`};
 const reportTable=(title,headers,body)=>`<h2>${title}</h2><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${body}</tbody></table>`;
 const bind=()=>document.getElementById("downloadReport")?.addEventListener("click",()=>{const w=window.open("","_blank");if(!w)return CF.toast("Please allow pop-ups to download the report.","error");const stock=data.products.map(p=>`<tr><td>${CF.escape(p.name)}</td><td>${CF.escape(p.productCode||"—")}</td><td>${CF.formatNumber(p.currentStock)}</td><td>${CF.formatNumber(p.minimumStock)}</td></tr>`).join("");const customers=data.customers.map(c=>`<tr><td>${CF.escape(c.name)}</td><td>${CF.escape(c.mobile||"—")}</td><td>${CF.escape(c.address||"—")}</td><td>${CF.formatCurrency(c.outstanding)}</td></tr>`).join("");const dues=data.invoices.filter(i=>Number(i.due)>0).map(i=>`<tr><td>${CF.escape(i.customerName)}</td><td>${CF.escape(i.invoiceNo)}</td><td>${i.invoiceDate}</td><td>${CF.formatCurrency(i.grandTotal)}</td><td>${CF.formatCurrency(i.due)}</td></tr>`).join("");w.document.write(`<!doctype html><title>Business Report</title><style>body{font:12px Arial;padding:20px;color:#111}h1{margin:0}h2{margin:25px 0 8px;font-size:16px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:18px}.card{border:1px solid #555;padding:10px}.card b{font-size:17px;display:block;margin-top:4px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #777;padding:6px;text-align:left;vertical-align:top}th{background:#eee}@media print{body{padding:0}}</style><h1>Click & Fix Technologies</h1><p>Business Detailed Report · ${new Date().toLocaleDateString("en-IN")}</p><div class="cards"><div class="card">Total Sales<b>${CF.formatCurrency(data.sales)}</b></div><div class="card">Total Purchase<b>${CF.formatCurrency(data.purchase)}</b></div><div class="card">Total Stock<b>${CF.formatNumber(data.stock)}</b></div><div class="card">Total Customers<b>${data.customers.length}</b></div><div class="card">Total Due Amount<b>${CF.formatCurrency(data.due)}</b></div></div>${reportTable("Product-wise Stock Summary",["Product","Product Code","Current Stock","Minimum Stock"],stock)}${reportTable("Customer List",["Customer","Mobile","Address","Total Due"],customers)}${reportTable("Invoice-wise Due Details",["Customer","Invoice No.","Invoice Date","Invoice Amount","Due Amount"],dues)}`);w.document.close();setTimeout(()=>w.print(),300)});
 return {render,bind};
})();
