"use strict";
window.CF = window.CF || {};
CF.router = (() => {
  const labels = { dashboard:"Dashboard", customers:"Customers", products:"Products", inventory:"Inventory", purchases:"Purchases & Suppliers", invoices:"Invoices", payments:"Payments", warranties:"Extension Warranty", reports:"Reports", dues:"Due List & Reminders", emailTemplates:"Email Templates", campaigns:"Bulk Email Campaigns", backup:"Backup & Restore", settings:"Settings" };
  const placeholder = route => `<article class="card placeholder"><h2>${labels[route]}</h2><p>This module is scheduled for v1.5.</p></article>`;
  const dashboard = async () => {
    const [customers, products, inventory, invoices, payments] = await Promise.all(["customers","products","inventory","invoices","payments"].map(CF.db.getAll));
    const today = CF.today(), month=today.slice(0,7); const todaySales = invoices.filter(i => i.invoiceDate === today).reduce((total,i)=>total+Number(i.grandTotal || 0),0); const monthlySales=invoices.filter(i=>i.invoiceDate?.startsWith(month)).reduce((total,i)=>total+Number(i.grandTotal||0),0), due = invoices.reduce((total,i)=>total+Number(i.due || 0),0), stock=products.reduce((t,p)=>t+Number(p.currentStock||0),0), recent=invoices.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5);
    return `<div class="stats"><div class="card"><span class="card-label">Total Customers</span><strong class="card-value">${CF.formatNumber(customers.length)}</strong></div><div class="card"><span class="card-label">Total Products</span><strong class="card-value">${CF.formatNumber(products.length)}</strong></div><div class="card"><span class="card-label">Total Stock</span><strong class="card-value">${CF.formatNumber(stock)}</strong></div><div class="card"><span class="card-label">Total Invoices</span><strong class="card-value">${CF.formatNumber(invoices.length)}</strong></div><div class="card"><span class="card-label">Today's Sale</span><strong class="card-value card-accent">${CF.formatCurrency(todaySales)}</strong></div><div class="card"><span class="card-label">Monthly Sale</span><strong class="card-value card-accent">${CF.formatCurrency(monthlySales)}</strong></div><div class="card"><span class="card-label">Pending Payment</span><strong class="card-value">${CF.formatCurrency(due)}</strong></div></div><div class="section-grid"><article class="card"><h2 class="section-title">Recent Invoices</h2>${recent.length?`<table><thead><tr><th>Invoice</th><th>Customer</th><th>Total</th><th>Due</th></tr></thead><tbody>${recent.map(i=>`<tr><td>${CF.escape(i.invoiceNo)}</td><td>${CF.escape(i.customerName)}</td><td>${CF.formatCurrency(i.grandTotal)}</td><td>${CF.formatCurrency(i.due)}</td></tr>`).join("")}</tbody></table>`:"<p class='empty'>No invoices yet.</p>"}</article><aside class="notice"><strong>Offline-first foundation ready</strong><br>All saved data stays on this device in IndexedDB. Use JSON Backup before moving to another device.</aside></div>`;
  };
  const render = async () => { const requested = location.hash.slice(1) || "dashboard"; const route = labels[requested] ? requested : "dashboard"; document.getElementById("pageTitle").textContent = labels[route]; document.querySelectorAll(".nav-link").forEach(link=>link.classList.toggle("active",link.dataset.route===route)); const module=CF[route]; document.getElementById("view").innerHTML = route === "dashboard" ? await dashboard() : module?.render ? await module.render() : placeholder(route); module?.bind?.(); CF.sidebar?.close(); };
  return { render };
})();
