"use strict";
window.CF = window.CF || {};
CF.settings = (() => {
 const fields=["companyName","address","phone","email","gst","bank","upi","qrImageUrl","invoicePrefix","nextInvoiceNumber","defaultDeliveryTerms","invoiceTerms"];
 const labels={companyName:"Company Name",address:"Address",phone:"Phone",email:"Email",gst:"GST Number",bank:"Bank Details (shown under Scan & Pay)",upi:"UPI ID",qrImageUrl:"UPI QR image path / URL",invoicePrefix:"Invoice Prefix",nextInvoiceNumber:"Next Invoice Number",defaultDeliveryTerms:"Default Delivery Terms (shown on every invoice)",invoiceTerms:"Terms & Conditions (one point per line; shown on every invoice)"};
 const areas=new Set(["address","bank","defaultDeliveryTerms","invoiceTerms"]),templates=[["fullA4","Template 1 — Full A4"],["halfA4","Template 2 — A4 Half Page"],["modernCompact","Template 3 — Modern Compact"],["professionalBusiness","Template 4 — Professional Business"]];
 const render=async()=>{const all=await CF.db.getAll("settings"),s=Object.fromEntries(all.map(x=>[x.key,x.value])),field=k=>`<label class="${areas.has(k)?"wide":""}">${labels[k]}${areas.has(k)?`<textarea name="${k}">${CF.escape(s[k]||"")}</textarea>`:`<input name="${k}" value="${CF.escape(s[k]||"")}" ${k==="invoicePrefix"?"placeholder=CF-":""} ${k==="nextInvoiceNumber"?"placeholder=000001":""}>`}</label>`;return `<article class="card"><h2 class="section-title">Company & Invoice Settings</h2><p class="notice">Enter your terms and delivery terms once here. The selected invoice template is used consistently for print, PDF, and invoice-email attachments.</p><form id="settingsForm" class="form-grid">${fields.map(field).join("")}<fieldset class="wide invoice-template-settings"><legend>Invoice Template</legend><p class="muted">Choose the default document layout.</p>${templates.map(([value,label])=>`<label><input type="radio" name="invoiceTemplate" value="${value}" ${(s.invoiceTemplate||"fullA4")===value?"checked":""}> ${label}</label>`).join("")}</fieldset><div class="form-actions wide"><button class="primary">Save Settings</button></div></form></article>`};
 const bind=()=>document.getElementById("settingsForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=new FormData(e.target);for(const [key,value] of form)await CF.db.put("settings",{key,value,updatedAt:new Date().toISOString()});const next=Number(form.get("nextInvoiceNumber"));if(Number.isFinite(next)&&next>0)await CF.db.put("counters",{name:"INV-",value:next-1,updatedAt:new Date().toISOString()});CF.toast("Company settings saved")});
 return {render,bind};
})();
