import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@5.9.6";

const cors = { "Access-Control-Allow-Origin": "https://billing.clickandfix.site", "Access-Control-Allow-Headers": "authorization, content-type, apikey", "Access-Control-Allow-Methods": "POST, OPTIONS" };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
const encoder = new TextEncoder();
const hash = async (value: string) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(value)))).map(byte => byte.toString(16).padStart(2, "0")).join("");
const random = (bytes = 32) => { const values = new Uint8Array(bytes); crypto.getRandomValues(values); return btoa(String.fromCharCode(...values)).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); };
const otp = () => String(crypto.getRandomValues(new Uint32Array(1))[0] % 1_000_000).padStart(6, "0");
const normalPhone = (value: unknown) => String(value || "").replace(/\D/g, "").replace(/^91(?=\d{10}$)/, "");
const requestMeta = (request: Request) => ({ ip: request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || null, userAgent: request.headers.get("user-agent") || null });
const publicBase = "https://billing.clickandfix.site/acknowledgement.html";
const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!, { auth: { persistSession: false } });
const firebaseProject = Deno.env.get("FIREBASE_PROJECT_ID") || "click-n-fix-crm";
const firebaseKeys = createRemoteJWKSet(new URL("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"));

async function admin(request: Request) {
  const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
  if (!token) throw new Error("Admin authentication is required.");
  const result = await jwtVerify(token, firebaseKeys, { issuer: `https://securetoken.google.com/${firebaseProject}`, audience: firebaseProject });
  const email = String(result.payload.email || "").toLowerCase(), allowed = new Set((Deno.env.get("FIREBASE_ADMIN_EMAILS") || "").split(",").map(value => value.trim().toLowerCase()).filter(Boolean));
  if (!result.payload.sub || !email || !allowed.size || !allowed.has(email)) throw new Error("Firebase account is not authorized for acknowledgement administration.");
  return { uid: result.payload.sub, email };
}
async function event(acknowledgementId: string, eventType: string, request: Request, metadata: Record<string, unknown> = {}) {
  const meta = requestMeta(request);
  await supabase.from("ack_events").insert({ acknowledgement_id: acknowledgementId, event_type: eventType, ip: meta.ip, user_agent: meta.userAgent, metadata });
}
function assertString(input: unknown, name: string, maximum = 1000) { const value = String(input || "").trim(); if (!value || value.length > maximum) throw new Error(`Invalid ${name}.`); return value; }
function validEmail(value: string) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value); }
async function findByAccessToken(token: unknown) { const tokenValue = assertString(token, "access token", 512); const { data, error } = await supabase.from("acknowledgements").select("*").eq("access_token_hash", await hash(tokenValue)).maybeSingle(); if (error || !data) throw new Error("Acknowledgement link is invalid."); if (data.status === "VOID") throw new Error("This acknowledgement has been voided."); if (new Date(data.token_expires_at).getTime() < Date.now()) throw new Error("This acknowledgement link has expired."); return data; }
async function verifiedAck(token: unknown, verificationToken: unknown) { const ack = await findByAccessToken(token); const supplied = assertString(verificationToken, "verification session", 512); if (!ack.verification_token_hash || await hash(supplied) !== ack.verification_token_hash || !ack.verification_expires_at || new Date(ack.verification_expires_at).getTime() < Date.now()) throw new Error("Verification session has expired. Please verify your identity again."); return ack; }
async function sendBrevo(to: string, subject: string, htmlContent: string) {
  const apiKey = Deno.env.get("BREVO_API_KEY"), senderEmail = Deno.env.get("BREVO_SENDER_EMAIL"), senderName = Deno.env.get("BREVO_SENDER_NAME");
  if (!apiKey || !senderEmail || !senderName) throw new Error("OTP email service is not configured.");
  const response = await fetch("https://api.brevo.com/v3/smtp/email", { method: "POST", headers: { "content-type": "application/json", "api-key": apiKey }, body: JSON.stringify({ sender: { email: senderEmail, name: senderName }, to: [{ email: to }], subject, htmlContent }) });
  if (!response.ok) throw new Error("OTP email could not be sent.");
}

Deno.serve(async request => {
  if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
  if (request.method !== "POST") return json({ error: "POST required" }, 405);
  try {
    const input = await request.json(), action = assertString(input.action, "action", 64);
    if (action === "admin-create") {
      const actor = await admin(request), invoiceId = assertString(input.invoiceId, "invoice ID"), invoiceNo = assertString(input.invoiceNo, "invoice number"), customerId = assertString(input.customerId, "customer ID"), customerName = assertString(input.customerName, "customer name"), customerEmail = assertString(input.customerEmail, "customer email").toLowerCase(), customerMobile = normalPhone(input.customerMobile), invoiceDate = assertString(input.invoiceDate, "invoice date", 10), deliveryDate = assertString(input.deliveryDate, "delivery date", 10), invoiceTotal = Number(input.invoiceTotal), signatureMethod = input.signatureMethod === "physical" ? "physical" : "digital";
      if (!validEmail(customerEmail) || customerMobile.length !== 10 || !Number.isFinite(invoiceTotal) || invoiceTotal < 0) throw new Error("Acknowledgement customer or invoice data is invalid.");
      const sequence = `ACK-${new Date().getFullYear()}-${random(6).toUpperCase()}`, rawToken = random(48), expires = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
      const { data, error } = await supabase.from("acknowledgements").insert({ acknowledgement_no: sequence, invoice_id: invoiceId, invoice_no: invoiceNo, customer_id: customerId, customer_name: customerName, customer_email: customerEmail, customer_mobile: customerMobile, customer_address: String(input.customerAddress || ""), customer_gstin: String(input.customerGstin || ""), invoice_date: invoiceDate, delivery_date: deliveryDate, invoice_total: invoiceTotal, signature_method: signatureMethod, access_token_hash: await hash(rawToken), token_expires_at: expires, created_by_firebase_uid: actor.uid }).select().single();
      if (error) throw new Error("Acknowledgement could not be created.");
      await event(data.id, "CREATED", request, { actor: actor.uid, invoiceId });
      // A customer token is issued only by the send/resend action, never returned to the admin UI.
      return json({ acknowledgement: data }, 201);
    }
    if (action === "admin-send" || action === "admin-resend") {
      await admin(request); const ackId = assertString(input.acknowledgementId, "acknowledgement ID"); const { data: ack, error } = await supabase.from("acknowledgements").select("*").eq("id", ackId).maybeSingle(); if (error || !ack || ack.status === "VOID") throw new Error("Acknowledgement is unavailable."); const rawToken = random(48), expires = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), url = `${publicBase}?token=${encodeURIComponent(rawToken)}`;
      await sendBrevo(ack.customer_email, `Acknowledgement ${ack.acknowledgement_no}`, `<p>Hello ${ack.customer_name},</p><p>Please verify and sign your delivery acknowledgement:</p><p><a href="${url}">Open acknowledgement</a></p>`); await supabase.from("acknowledgements").update({ status: "SENT", access_token_hash: await hash(rawToken), token_expires_at: expires, otp_hash: null, otp_expires_at: null, verification_token_hash: null, verification_expires_at: null }).eq("id", ack.id); await event(ack.id, action === "admin-resend" ? "RESENT" : "SENT", request); return json({ success: true });
    }
    if (action === "admin-list") { await admin(request); const { data, error } = await supabase.from("acknowledgements").select("id,acknowledgement_no,invoice_id,invoice_no,customer_id,customer_name,delivery_date,invoice_total,status,signature_method,created_at,signed_at,voided_at,physical_document_url").order("created_at", { ascending: false }); if (error) throw new Error("Acknowledgement list could not be loaded."); return json({ acknowledgements: data || [] }); }
    if (action === "admin-get") { const actor = await admin(request), ackId = assertString(input.acknowledgementId, "acknowledgement ID"); const fields = "id,acknowledgement_no,invoice_id,invoice_no,customer_id,customer_name,customer_email,customer_mobile,customer_address,customer_gstin,invoice_date,delivery_date,invoice_total,status,signature_method,delivery_location,latitude,longitude,location_address,receiver_name,condition_confirmed,issue_remark,signature_data,signed_at,signed_ip,otp_verified_at,verified_email,verification_method,verified_ip,physical_document_url,physical_document_name,physical_document_uploaded_at,physical_document_notes,created_at,updated_at,voided_at,void_reason"; const { data: acknowledgement, error } = await supabase.from("acknowledgements").select(fields).eq("id", ackId).maybeSingle(); if (error || !acknowledgement) throw new Error("Acknowledgement not found."); const { data: events } = await supabase.from("ack_events").select("event_type,created_at,metadata").eq("acknowledgement_id", ackId).order("created_at", { ascending: false }); await event(ackId, "ADMIN_VIEWED", request, { actor: actor.uid }); return json({ acknowledgement, events: events || [] }); }
    if (action === "public-read") { const ack = await findByAccessToken(input.token); await event(ack.id, "PAGE_OPENED", request); return json({ acknowledgement: { acknowledgementNo: ack.acknowledgement_no, invoiceNo: ack.invoice_no, invoiceDate: ack.invoice_date, deliveryDate: ack.delivery_date, customerName: ack.customer_name, customerAddress: ack.customer_address, customerMobile: ack.customer_mobile, customerEmail: ack.customer_email, customerGstin: ack.customer_gstin, invoiceTotal: ack.invoice_total, status: ack.status, signatureMethod: ack.signature_method, receiverName: ack.receiver_name, conditionConfirmed: ack.condition_confirmed, issueRemark: ack.issue_remark, signatureData: ack.signature_data, signedAt: ack.signed_at, signedIp: ack.signed_ip, verifiedAt: ack.otp_verified_at, verificationMethod: ack.verification_method, deliveryLocation: ack.delivery_location, latitude: ack.latitude, longitude: ack.longitude } }); }
    if (action === "request-otp") { const ack = await findByAccessToken(input.token); if (ack.status === "SIGNED") return json({ error: "This acknowledgement has already been signed." }, 409); if (ack.otp_requested_at && Date.now() - new Date(ack.otp_requested_at).getTime() < 60_000) throw new Error("Please wait one minute before requesting another OTP."); if (normalPhone(input.phone) !== normalPhone(ack.customer_mobile)) throw new Error("Phone number does not match this acknowledgement."); const code = otp(), requestedAt = new Date().toISOString(); await sendBrevo(ack.customer_email, "Your Click & Fix acknowledgement OTP", `<p>Your one-time verification code is <b style="font-size:22px">${code}</b>.</p><p>It expires in 10 minutes.</p>`); await supabase.from("acknowledgements").update({ status: "PENDING_VERIFICATION", otp_hash: await hash(code), otp_expires_at: new Date(Date.now() + 10 * 60 * 1000).toISOString(), otp_requested_at: requestedAt, otp_attempts: 0 }).eq("id", ack.id); await event(ack.id, "OTP_REQUESTED", request); return json({ success: true }); }
    if (action === "verify-otp") { const ack = await findByAccessToken(input.token), code = assertString(input.otp, "OTP", 6); if (!ack.otp_hash || !ack.otp_expires_at || new Date(ack.otp_expires_at).getTime() < Date.now() || ack.otp_attempts >= 5) throw new Error("OTP has expired or is no longer valid."); if (await hash(code) !== ack.otp_hash) { await supabase.from("acknowledgements").update({ otp_attempts: ack.otp_attempts + 1 }).eq("id", ack.id); throw new Error("OTP is invalid."); } const session = random(32), meta = requestMeta(request), verifiedAt = new Date().toISOString(); await supabase.from("acknowledgements").update({ status: "VERIFIED", otp_hash: null, otp_expires_at: null, otp_verified_at: verifiedAt, verified_email: ack.customer_email, verification_method: "Email OTP", verified_ip: meta.ip, verification_token_hash: await hash(session), verification_expires_at: new Date(Date.now() + 30 * 60 * 1000).toISOString() }).eq("id", ack.id); await event(ack.id, "OTP_VERIFIED", request, { email: ack.customer_email }); return json({ verificationToken: session, verifiedAt, serverIp: meta.ip }); }
    if (action === "capture-location") { const ack = await findByAccessToken(input.token), latitude = Number(input.latitude), longitude = Number(input.longitude); if (!Number.isFinite(latitude) || !Number.isFinite(longitude) || Math.abs(latitude) > 90 || Math.abs(longitude) > 180) throw new Error("Valid location is required."); const location = String(input.locationAddress || `${latitude}, ${longitude}`).slice(0, 1000); await supabase.from("acknowledgements").update({ latitude, longitude, location_address: String(input.locationAddress || "").slice(0, 1000), delivery_location: location }).eq("id", ack.id); await event(ack.id, "LOCATION_CAPTURED", request, { latitude, longitude, location }); return json({ success: true, deliveryLocation: location }); }
    if (action === "signature-started") { const ack = await verifiedAck(input.token, input.verificationToken); await event(ack.id, "SIGNATURE_STARTED", request); return json({ success: true }); }
    if (action === "download-signed") { const ack = await findByAccessToken(input.token); if (ack.status !== "SIGNED") throw new Error("A signed acknowledgement is not available yet."); await event(ack.id, "PDF_DOWNLOADED", request); return json({ acknowledgement: { acknowledgementNo: ack.acknowledgement_no, invoiceNo: ack.invoice_no, invoiceDate: ack.invoice_date, deliveryDate: ack.delivery_date, customerName: ack.customer_name, customerAddress: ack.customer_address, customerMobile: ack.customer_mobile, customerEmail: ack.customer_email, invoiceTotal: ack.invoice_total, receiverName: ack.receiver_name, conditionConfirmed: ack.condition_confirmed, issueRemark: ack.issue_remark, signatureData: ack.signature_data, signedAt: ack.signed_at, signedIp: ack.signed_ip, verifiedAt: ack.otp_verified_at, verificationMethod: ack.verification_method, deliveryLocation: ack.delivery_location, latitude: ack.latitude, longitude: ack.longitude, signatureMethod: ack.signature_method } }); }
    if (action === "submit-signature") { const ack = await verifiedAck(input.token, input.verificationToken); if (ack.status === "SIGNED") return json({ error: "This acknowledgement has already been signed." }, 409); if (ack.latitude === null || ack.longitude === null) throw new Error("Location verification is required before signing."); const signature = assertString(input.signatureData, "signature", 350000), receiverName = assertString(input.receiverName, "receiver name", 200); if (!input.conditionConfirmed || !/^data:image\/(png|webp);base64,/.test(signature)) throw new Error("Receipt confirmation and a valid signature are required."); const { data: signed, error: signError } = await supabase.from("acknowledgements").update({ status: "SIGNED", signature_method: "digital", receiver_name: receiverName, condition_confirmed: true, issue_remark: String(input.issueRemark || "").slice(0, 1000), signature_data: signature, signed_at: new Date().toISOString(), signed_ip: requestMeta(request).ip, verification_token_hash: null, verification_expires_at: null }).eq("id", ack.id).eq("status", "VERIFIED").select("id").maybeSingle(); if (signError || !signed) throw new Error("This acknowledgement has already been signed or its verification session has expired."); await event(ack.id, "SIGNED", request); return json({ success: true }); }
    if (action === "admin-void" || action === "admin-add-physical-document" || action === "admin-view") { const actor = await admin(request), ackId = assertString(input.acknowledgementId, "acknowledgement ID"); const { data: ack } = await supabase.from("acknowledgements").select("*").eq("id", ackId).maybeSingle(); if (!ack) throw new Error("Acknowledgement not found."); if (action === "admin-void") { await supabase.from("acknowledgements").update({ status: "VOID", voided_at: new Date().toISOString(), void_reason: assertString(input.reason, "void reason", 1000) }).eq("id", ack.id); await event(ack.id, "VOIDED", request, { actor: actor.uid }); } else if (action === "admin-add-physical-document") { const documentUrl = assertString(input.url, "physical document URL", 2000); await supabase.from("acknowledgements").update({ signature_method: "physical", physical_document_url: documentUrl, physical_document_name: String(input.fileName || "Signed physical acknowledgement").slice(0, 255), physical_document_notes: String(input.notes || "").slice(0, 1000), physical_document_uploaded_at: new Date().toISOString() }).eq("id", ack.id); await event(ack.id, "PHYSICAL_DOCUMENT_ADDED", request, { actor: actor.uid, documentUrl }); } else await event(ack.id, "ADMIN_VIEWED", request, { actor: actor.uid }); return json({ acknowledgement: ack, success: true }); }
    return json({ error: "Unknown action." }, 400);
  } catch (error) { console.error(error); return json({ error: error instanceof Error ? error.message : "Acknowledgement request failed." }, 400); }
});
