"use strict";
window.CF = window.CF || {};
CF.backup = (() => {
 const stores=["customers","products","inventory","invoices","payments","settings","counters"];
 const driveSection = state => `<article class="card" id="googleDriveBackup"><h2 class="section-title">Google Drive Backup</h2><p class="notice">Your data stays in IndexedDB. Google Drive is used only when you manually back up or restore the single file <strong>clickfix_database.json</strong>.</p><div class="form-grid"><label>Google Account<input readonly value="${CF.escape(state.email ? `${state.name}${state.name ? " — " : ""}${state.email}` : "Not signed in")}"></label><label>Drive Status<input readonly value="${state.signedIn ? "Connected" : state.email ? "Sign in required" : "Not connected"}"></label><label>Last Backup Time<input readonly value="${CF.escape(state.lastBackup ? new Date(state.lastBackup).toLocaleString("en-IN") : "No backup recorded")}"></label></div><div class="form-actions" style="margin-top:14px"><button type="button" class="primary" id="googleSignIn" ${state.signedIn ? "disabled" : ""}>Sign In</button><button type="button" class="secondary" id="googleSignOut" ${state.signedIn ? "" : "disabled"}>Sign Out</button><button type="button" class="primary" id="googleBackupNow">Backup Now</button><button type="button" class="secondary" id="googleRestore">Restore Backup</button></div></article>`;
 const render=async()=>{const state=await CF.sync.status();return `<div class="section-grid"><article class="card"><h2 class="section-title">Export JSON Backup</h2><p>Download a complete local backup. Store it safely before changing computers.</p><button id="exportBackup" class="primary">Download backup.json</button></article><article class="card"><h2 class="section-title">Restore JSON Backup</h2><p>Restoring merges backup records with this device's local data.</p><input id="restoreBackup" type="file" accept="application/json"><p><button id="restoreButton" class="primary">Restore Backup</button></p></article></div>${driveSection(state)}`};
 const bind=()=>{document.getElementById("exportBackup")?.addEventListener("click",async()=>{const data={app:"Click & Fix Billing Pro",version:"1.0",exportedAt:new Date().toISOString(),stores:{}};for(const s of stores)data.stores[s]=await CF.db.getAll(s);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`clickfix-backup-${CF.today()}.json`;a.click();URL.revokeObjectURL(url)});document.getElementById("restoreButton")?.addEventListener("click",async()=>{const file=document.getElementById("restoreBackup").files[0];if(!file)return CF.toast("Choose a backup file","error");try{const data=JSON.parse(await file.text());if(!data.stores)throw Error();for(const s of stores)for(const row of data.stores[s]||[])await CF.db.put(s,row);CF.toast("Backup restored");CF.router.render()}catch{CF.toast("This is not a valid Click & Fix backup","error")}});document.getElementById("googleSignIn")?.addEventListener("click",CF.sync.signIn);document.getElementById("googleSignOut")?.addEventListener("click",CF.sync.signOut);document.getElementById("googleBackupNow")?.addEventListener("click",CF.sync.backup);document.getElementById("googleRestore")?.addEventListener("click",()=>{if(confirm("Restore will replace all local Click & Fix data with the Google Drive backup. Continue?"))CF.sync.restore();});document.addEventListener("cf:sync-status",()=>{if(location.hash==="#backup")CF.router.render();},{once:true});};
 return {render,bind};
})();
