"use strict";
window.CF = window.CF || {};
CF.formatCurrency = value => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(Number(value || 0));
CF.formatNumber = value => new Intl.NumberFormat("en-IN").format(Number(value || 0));
CF.toast = (message, type = "info") => { const node = document.createElement("div"); node.className = `toast ${type === "error" ? "error" : ""}`; node.textContent = message; document.getElementById("toastHost").append(node); setTimeout(() => node.remove(), 3500); };
CF.today = () => new Date().toISOString().slice(0, 10);
CF.escape = value => String(value ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
CF.id = () => crypto.randomUUID();
CF.money = value => Math.round((Number(value) || 0) * 100) / 100;
CF.amountWords = value => { const n = Math.floor(Number(value) || 0); if (!n) return "Zero Rupees Only"; const ones=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"], tens=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"]; const say=x=>x<20?ones[x]:x<100?`${tens[Math.floor(x/10)]}${x%10?" "+ones[x%10]:""}`:x<1000?`${ones[Math.floor(x/100)]} Hundred${x%100?" "+say(x%100):""}`:x<100000?`${say(Math.floor(x/1000))} Thousand${x%1000?" "+say(x%1000):""}`:x<10000000?`${say(Math.floor(x/100000))} Lakh${x%100000?" "+say(x%100000):""}`:`${say(Math.floor(x/10000000))} Crore${x%10000000?" "+say(x%10000000):""}`; return `${say(n)} Rupees Only`; };
CF.confirmDelete = async (store, key, message = "Delete this record?") => { if (!confirm(message)) return; await CF.db.remove(store, key); CF.toast("Record deleted"); CF.router.render(); };
