"use strict";
window.CF = window.CF || {};
CF.settings = (() => {
 const fields=["companyName","address","phone","email","gst","bank","upi","qrImageUrl","invoicePrefix","nextInvoiceNumber","defaultDeliveryTerms","invoiceTerms"];
 const labels={companyName:"Company Name",address:"Address",phone:"Phone",email:"Email",gst:"GST Number",bank:"Bank Details (shown under Scan & Pay)",upi:"UPI ID",qrImageUrl:"UPI QR image path / URL",invoicePrefix:"Invoice Prefix",nextInvoiceNumber:"Next Invoice Number",defaultDeliveryTerms:"Default Delivery Terms (shown on every invoice)",invoiceTerms:"Terms & Conditions (one point per line; shown on every invoice)"};
 const areas=new Set(["address","bank","defaultDeliveryTerms","invoiceTerms"]);
 const render=async()=>{const all=await CF.db.getAll("settings"),s=Object.fromEntries(all.map(x=>[x.key,x.value]));return `<article class="card"><h2 class="section-title">Company & Invoice Settings</h2><p class="notice">Enter your terms and delivery terms once here. They will automatically appear on every invoice PDF. Add your UPI QR image path or URL to show it in Scan & Pay.</p><form id="settingsForm" class="form-grid">${fields.map(k=>`<label class="${areas.has(k)?"wide":""}">${labels[k]}${areas.has(k)?`<textarea name="${k}">${CF.escape(s[k]||"")}</textarea>`:`<input name="${k}" value="${CF.escape(s[k]||"")}" ${k==="invoicePrefix"?"placeholder=CF-":""} ${k==="nextInvoiceNumber"?"placeholder=000001":""}>`}</label>`).join("")}<div class="form-actions wide"><button class="primary">Save Settings</button></div></form></article>`};
 const bind=()=>document.getElementById("settingsForm")?.addEventListener("submit",async e=>{e.preventDefault();const form=new FormData(e.target);for(const [key,value] of form)await CF.db.put("settings",{key,value,updatedAt:new Date().toISOString()});const next=Number(form.get("nextInvoiceNumber"));if(Number.isFinite(next)&&next>0)await CF.db.put("counters",{name:"INV-",value:next-1,updatedAt:new Date().toISOString()});CF.toast("Company settings saved")});
 return {render,bind};
})();
